import type { DocumentedClaim } from "./types.js";

/**
 * Claims taken from the world, each with a source.
 *
 * The divergence detector checks these against the oracle's EXECUTED results.
 * `predicts` is what the claim leads you to expect for `vectorId`; when the
 * engine or the policy says otherwise, the claim is flagged.
 *
 * Sources are real. Folklore entries are paraphrases of the advice they
 * represent, not verbatim quotations, and the URL points at the canonical
 * thread or document.
 */
export const CLAIMS: DocumentedClaim[] = [
  {
    id: "folklore-nocase-unique",
    kind: "folklore",
    engine: "SQLite",
    source:
      'Stack Overflow, "How to make a case-insensitive unique column in SQLite" (answer score 300+, 2013)',
    sourceUrl: "https://stackoverflow.com/questions/20914946/how-to-make-a-case-insensitive-unique-column-in-sqlite",
    vectorId: "unicode-case",
    predicts: "COLLIDES",
    text: "Declare the column COLLATE NOCASE and your uniqueness problem is solved.",
    target: { kind: "engine", engineFamily: "sqlite/nocase" },
  },
  {
    id: "vendor-sqlite-nocase-ascii",
    kind: "vendor-doc",
    engine: "SQLite",
    source: "sqlite.org - Datatypes In SQLite, section 3.1 (Built-in Collating Sequences)",
    sourceUrl: "https://sqlite.org/datatype3.html#collation",
    vectorId: "unicode-case",
    predicts: "DISTINCT",
    text: "NOCASE folds only the 26 upper case characters of ASCII to lower case before comparing.",
    target: { kind: "engine", engineFamily: "sqlite/nocase" },
  },
  {
    id: "vendor-sqlite-binary",
    kind: "vendor-doc",
    engine: "SQLite",
    source: "sqlite.org - Datatypes In SQLite, section 3.1 (BINARY is the default)",
    sourceUrl: "https://sqlite.org/datatype3.html#collation",
    vectorId: "ascii-case",
    predicts: "DISTINCT",
    text: "BINARY is the default collation and compares strings byte for byte.",
    target: { kind: "engine", engineFamily: "sqlite/binary" },
  },
  {
    id: "folklore-lowercase-email",
    kind: "folklore",
    engine: "application",
    source: "Widespread practice - \"just lowercase the email address before storing it\"",
    sourceUrl: "https://stackoverflow.com/search?q=lowercase+email+unique",
    vectorId: "sharp-s",
    predicts: "COLLIDES",
    text: "Lower-casing the address before insert removes case-driven duplicates.",
    target: { kind: "policy", policyId: "python.lower" },
  },
  {
    id: "folklore-lowercase-email-js",
    kind: "folklore",
    engine: "application",
    source: "Widespread practice - toLowerCase() applied to the e-mail column in Node",
    sourceUrl: "https://stackoverflow.com/search?q=lowercase+email+unique",
    vectorId: "sharp-s",
    predicts: "COLLIDES",
    text: "toLowerCase() before insert removes case-driven duplicates.",
    target: { kind: "policy", policyId: "js.toLowerCase" },
  },
  {
    id: "vendor-mysql-pad-space",
    kind: "vendor-doc",
    engine: "MySQL",
    source: "dev.mysql.com - Character Sets, Collations, Unicode, section 10.9.1 (The _bin Collations for Unicode)",
    sourceUrl: "https://dev.mysql.com/doc/refman/8.0/en/unicode-charset-unicode.html",
    vectorId: "trailing-space",
    predicts: "COLLIDES",
    text: "Older MySQL collations such as utf8mb4_general_ci are PAD SPACE: 'a' and 'a ' compare equal inside a unique index.",
    target: { kind: "engine", engineFamily: "mysql/utf8mb4_general_ci" },
  },
  {
    id: "vendor-mysql-0900-nopad",
    kind: "vendor-doc",
    engine: "MySQL",
    source: "dev.mysql.com - Unicode Character Sets, 10.9.2 The utf8mb4 Collations (0900 family are NO PAD)",
    sourceUrl: "https://dev.mysql.com/doc/refman/8.0/en/unicode-charset.html",
    vectorId: "trailing-space",
    predicts: "DISTINCT",
    text: "The utf8mb4_0900_* family introduced in MySQL 8.0 is NO PAD, so 'a' and 'a ' stay two distinct rows in the very same table definition.",
    target: { kind: "engine", engineFamily: "mysql/utf8mb4_0900_ai_ci" },
  },
  {
    id: "vendor-mysql-0900-ai-ci",
    kind: "vendor-doc",
    engine: "MySQL",
    source: "dev.mysql.com - Unicode Character Sets, utf8mb4_0900_ai_ci",
    sourceUrl: "https://dev.mysql.com/doc/refman/8.0/en/unicode-charset.html",
    vectorId: "accent-fold",
    predicts: "COLLIDES",
    text: "utf8mb4_0900_ai_ci is case- and accent-insensitive, so Jose and José collide.",
    target: { kind: "engine", engineFamily: "mysql/utf8mb4_0900_ai_ci" },
  },
  {
    id: "vendor-postgres-nondeterministic",
    kind: "vendor-doc",
    engine: "PostgreSQL",
    source: "postgresql.org - CREATE COLLATION, nondeterministic subtransactions note (deterministic = false)",
    sourceUrl: "https://www.postgresql.org/docs/current/sql-createcollation.html",
    vectorId: "accent-fold",
    predicts: "COLLIDES",
    text: "A nondeterministic ICU collation compares at the primary level only, so an accent does not prevent equality.",
    target: { kind: "engine", engineFamily: "postgres/primary-nondet" },
  },
  {
    id: "vendor-postgres-normalize",
    kind: "vendor-doc",
    engine: "PostgreSQL",
    source: "postgresql.org - normalize() (PostgreSQL 16 and later)",
    sourceUrl: "https://www.postgresql.org/docs/current/functions-string.html",
    vectorId: "nfc-nfd",
    predicts: "COLLIDES",
    text: "normalize(text, NFC) canonicalises both forms before an expression index compares them.",
    target: { kind: "policy", policyId: "postgres.normalize-nfc" },
  },
  {
    id: "spec-uts39-confusables",
    kind: "spec",
    engine: "all engines",
    source: "Unicode UTS #39 - Unicode Security Mechanisms, confusable detection",
    sourceUrl: "https://www.unicode.org/reports/tr39/",
    vectorId: "homoglyph",
    predicts: "DISTINCT",
    text: "Collation and normalisation do not fold confusable characters. Cyrillic a and Latin a stay distinct in every engine; only confusable detection catches them.",
    target: { kind: "engine", engineFamily: "sqlite/binary" },
  },
  {
    id: "spec-uax15-nfkc",
    kind: "spec",
    engine: "application",
    source: "Unicode UAX #15 - Unicode Normalization Forms, section 6 Compatibility Decomposition",
    sourceUrl: "https://www.unicode.org/reports/tr15/",
    vectorId: "fullwidth",
    predicts: "COLLIDES",
    text: "NFKC folds the compatibility decompositions, so fullwidth A becomes plain A.",
    target: { kind: "policy", policyId: "python.nfkc" },
  },
  {
    id: "spec-lower-vs-casefold",
    kind: "spec",
    engine: "application",
    source: "Unicode data - simple lowercase mapping vs full case folding (Python str.lower)",
    sourceUrl: "https://docs.python.org/3/library/stdtypes.html#str.lower",
    vectorId: "ligature",
    predicts: "DISTINCT",
    text: "str.lower() performs a simple lowercase mapping and leaves U+FB01 LATIN SMALL LIGATURE FI untouched, so it does not merge this pair.",
    target: { kind: "policy", policyId: "python.lower" },
  },
  {
    id: "spec-casefold-folds-ligature",
    kind: "spec",
    engine: "application",
    source: "Unicode CaseFolding.txt, status F (full) mappings, used by Python str.casefold",
    sourceUrl: "https://www.unicode.org/Public/UCD/latest/CaseFolding.txt",
    vectorId: "ligature",
    predicts: "COLLIDES",
    text: "str.casefold() applies the full case-folding mapping, which expands U+FB01 to the two ASCII letters 'fi'.",
    target: { kind: "policy", policyId: "python.casefold" },
  },
];
